# Generated by Django 4.0.5 on 2022-06-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntregable1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='oC',
            new_name='ordenCompra',
        ),
    ]
